'use client';

import { useMemo, useState } from 'react';

const applicationUrl = 'https://www.vunesp.com.br/VNSP2514';
const guideUrl = 'https://vestibular.unesp.br/Home/guiadeprofissoes51/guia-unesp-de-profissoes-2025-1.pdf';
const courses = [
  { name: 'Ciência da Computação', city: 'Bauru · Presidente Prudente · Rio Claro · São José do Rio Preto', area: 'Tecnologia', description: 'Algoritmos, programação e sistemas para resolver problemas complexos.', study: 'Lógica, matemática, algoritmos, programação, hardware e arquitetura de computadores.', work: 'Software, dados, inteligência artificial, segurança da informação, redes e computação em nuvem.', highlight: 'Há laboratórios, pesquisa e projetos práticos em todos os câmpus.' },
  { name: 'Direito', city: 'Franca', area: 'Humanas', description: 'Leitura crítica das normas e da vida social para promover justiça.', study: 'Constitucional, administrativo, penal, civil, trabalho, comercial e tributário, com base humanista.', work: 'Advocacia, concursos públicos, consultoria, assessoria legislativa, pesquisa e docência.', highlight: 'Prática jurídica, serviços à comunidade e acompanhamento de processos e audiências.' },
  { name: 'Engenharia Agronômica', city: 'Botucatu · Dracena · Ilha Solteira · Jaboticabal · Registro', area: 'Exatas', description: 'Ciência e tecnologia para a produção agrícola e animal sustentável.', study: 'Solo, plantas, produção, mecanização, economia rural, alimentos e gestão de projetos.', work: 'Agronegócio, cooperativas, agroindústrias, pesquisa, consultoria, mercado financeiro e propriedades rurais.', highlight: 'Fazendas experimentais, extensão e atuação conectada a territórios produtivos.' },
  { name: 'Medicina', city: 'Botucatu', area: 'Saúde', description: 'Formação científica e humanística para o cuidado integral em saúde.', study: 'Bases biológicas, fisiológicas e clínicas, integralidade do cuidado e habilidades médicas.', work: 'Atenção primária, urgência, hospitais, SUS, residência e diferentes especialidades.', highlight: 'Seis anos, com prática desde o início e internato de três anos.' },
  { name: 'Arquitetura e Urbanismo', city: 'Bauru · Presidente Prudente', area: 'Exatas', description: 'Projeto, cidade e território para tornar os lugares mais habitáveis.', study: 'Projeto, tecnologia, linguagem, práticas profissionais, urbanismo e patrimônio.', work: 'Construção, planejamento urbano e territorial, restauro, paisagismo e interiores.', highlight: 'Atividades de extensão tratam a cidade como laboratório de práticas aplicadas.' },
  { name: 'Ciências Biológicas', city: 'Assis · Bauru · Botucatu · Ilha Solteira · Jaboticabal · Rio Claro · São José do Rio Preto · São Vicente', area: 'Saúde', description: 'O estudo da vida, da biodiversidade e da relação humana com o ambiente.', study: 'Genética, biologia molecular, fauna, flora, ecologia, ambiente e educação.', work: 'Pesquisa, ensino, laboratórios, gestão ambiental, conservação, alimentos e vacinas.', highlight: 'Bacharelado e licenciatura; São Vicente oferece também ênfases em Biologia Marinha e Gerenciamento Costeiro.' },
  { name: 'Administração', city: 'Jaboticabal · Tupã', area: 'Humanas', description: 'Gestão estratégica de pessoas, recursos e organizações.', study: 'Finanças, produção, marketing, sistemas de informação, inovação e gestão ambiental.', work: 'Empresas, hospitais, escolas, organizações públicas, ONGs, marketing e novos negócios.', highlight: 'Intercâmbio, empresa júnior, pesquisa e projetos de extensão integram a formação.' },
  { name: 'Design', city: 'Bauru', area: 'Artes', description: 'Criatividade e tecnologia para melhorar produtos, sistemas e experiências.', study: 'Projetos visuais, produtos, interfaces, fotografia, ergonomia, fabricação digital e pesquisa.', work: 'Criação, direção de arte, conteúdo, curadoria, inovação, gestão e empreendedorismo.', highlight: 'Oficinas e laboratórios aproximam teoria, prática e experimentação.' },
  { name: 'Música', city: 'São Paulo', area: 'Artes', description: 'Formação de cantores, instrumentistas, regentes, compositores e professores.', study: 'Teoria musical, história e estética da música ocidental, escritura musical, performance e práticas pedagógicas.', work: 'Interpretação, composição, ensino, produção de material didático, direção de instituições e espetáculos, eventos e crítica cultural.', highlight: 'O Instituto de Artes oferece bacharelado e licenciatura; o ingresso inclui exame de habilidades musicais.' },
];
const detailedGuideCourses: Record<string, { description: string; study: string; work: string; highlight: string }> = {
  'Administração Pública': { description: 'Políticas públicas, gestão democrática e serviços que fazem diferença na vida coletiva.', study: 'Estado, orçamento, planejamento, direito administrativo, políticas sociais e avaliação de programas.', work: 'Prefeituras, secretarias, ministérios, câmaras, organizações sociais, consultoria e pesquisa.', highlight: 'Formação voltada a decisões públicas transparentes, eficientes e comprometidas com a cidadania.' },
  Arquivologia: { description: 'Organização, preservação e acesso responsável à memória e à informação.', study: 'Gestão de documentos, preservação, classificação, avaliação, digitalização e sistemas de informação.', work: 'Arquivos públicos e empresariais, centros de memória, museus, hospitais e instituições culturais.', highlight: 'Une Arquivologia e Ciência da Informação, com atividades práticas e estágios.' },
  'Arte-Teatro e Artes Cênicas': { description: 'Criação, interpretação e ensino de teatro como linguagem artística e social.', study: 'Atuação, direção, dramaturgia, pedagogia do teatro, corpo, voz, performance e cultura brasileira.', work: 'Escolas, grupos e companhias, projetos culturais, mediação, direção e produção de espetáculos.', highlight: 'Licenciatura que combina formação artística, pesquisa e prática pedagógica.' },
  'Artes Visuais': { description: 'Imagem, criação e pensamento crítico para produzir e ensinar arte.', study: 'Desenho, pintura, fotografia, vídeo, história e crítica da arte, processos digitais e educação.', work: 'Ensino, ateliês, curadoria, museus, produção cultural, audiovisual e projetos educativos.', highlight: 'Bacharelado e licenciatura, com extensão e experimentação em linguagens diversas.' },
  Biblioteconomia: { description: 'Mediação entre pessoas, informação, leitura e conhecimento.', study: 'Organização da informação, acervos, serviços de referência, gestão de bibliotecas e cultura digital.', work: 'Bibliotecas, centros de documentação, editoras, escolas, empresas, projetos de leitura e dados.', highlight: 'O curso dialoga diretamente com Arquivologia e Ciência da Informação.' },
  'Ciências Biomédicas': { description: 'Investigação dos processos biológicos e das doenças para gerar conhecimento em saúde.', study: 'Biologia celular e molecular, genética, imunologia, microbiologia, fisiologia e pesquisa experimental.', work: 'Pesquisa, laboratórios, diagnóstico, indústria farmacêutica, biotecnologia e docência.', highlight: 'Formação centrada em ciência básica e aplicada, com iniciação científica desde a graduação.' },
  'Ciências Econômicas': { description: 'Análise de escolhas, mercados e políticas que organizam a vida econômica.', study: 'Micro e macroeconomia, estatística, finanças, desenvolvimento, economia brasileira e métodos quantitativos.', work: 'Empresas, bancos, consultorias, setor público, pesquisa, planejamento e mercado financeiro.', highlight: 'Leitura crítica da economia com ferramentas para interpretar dados e formular políticas.' },
  'Ciências Sociais': { description: 'Compreensão da sociedade por meio da Sociologia, Antropologia e Ciência Política.', study: 'Teorias sociais, pesquisa de campo, cultura, desigualdades, política, estatística e métodos qualitativos.', work: 'Pesquisa, ensino, políticas públicas, organizações sociais, consultoria e comunicação.', highlight: 'Formação para analisar problemas contemporâneos e produzir pesquisa social rigorosa.' },
  'Comunicação: Rádio, TV e Internet': { description: 'Narrativas, tecnologia e produção audiovisual para meios tradicionais e digitais.', study: 'Roteiro, produção, edição, rádio, televisão, internet, linguagem audiovisual e cultura midiática.', work: 'Produtoras, emissoras, plataformas digitais, conteúdo, comunicação institucional e empreendedorismo.', highlight: 'Projetos e laboratórios aproximam a formação do cenário audiovisual em transformação.' },
  Ecologia: { description: 'Estudo das relações entre seres vivos, ambiente e conservação da biodiversidade.', study: 'Ecossistemas, biodiversidade, evolução, conservação, estatística, geoprocessamento e trabalho de campo.', work: 'Unidades de conservação, consultorias, licenciamento, pesquisa, educação e gestão ambiental.', highlight: 'Formação marcada por atividades de campo e investigação de problemas ambientais reais.' },
  'Educação Física': { description: 'Movimento, saúde, esporte e educação para diferentes públicos e contextos.', study: 'Corpo humano, treinamento, esporte, cultura corporal, pedagogia, saúde coletiva e gestão.', work: 'Escolas, clubes, academias, projetos sociais, reabilitação, pesquisa e gestão esportiva.', highlight: 'Integra prática, ciência e educação; as modalidades variam conforme o câmpus.' },
  Enfermagem: { description: 'Cuidado em saúde com base científica, ética e atenção às pessoas e comunidades.', study: 'Fundamentos de enfermagem, saúde coletiva, clínica, gestão, atenção à família e práticas assistenciais.', work: 'Hospitais, unidades básicas, urgência, saúde da família, gestão, pesquisa e ensino.', highlight: 'O cuidado se aprende em cenários reais do SUS, em diálogo com equipes multiprofissionais.' },
  'Engenharia Aeronáutica': { description: 'Tecnologia para projetar, construir e operar sistemas aeronáuticos e espaciais.', study: 'Aerodinâmica, estruturas, propulsão, materiais, sistemas embarcados, controle e projeto de aeronaves.', work: 'Indústria aeronáutica, defesa, manutenção, certificação, pesquisa, inovação e setor espacial.', highlight: 'Curso voltado a problemas complexos de mobilidade aérea e tecnologia de ponta.' },
  'Engenharia Ambiental': { description: 'Soluções técnicas para prevenir impactos e recuperar sistemas ambientais.', study: 'Água, solo, resíduos, saneamento, geoprocessamento, ecologia, legislação e avaliação de impactos.', work: 'Saneamento, licenciamento, consultorias, indústrias, órgãos públicos e projetos de restauração.', highlight: 'Disponível em diversos câmpus, com formações conectadas aos territórios e desafios ambientais.' },
  'Engenharia Civil': { description: 'Infraestrutura, edificações e cidades planejadas com segurança e responsabilidade.', study: 'Estruturas, materiais, geotecnia, hidráulica, transportes, construção e gestão de obras.', work: 'Construtoras, projetos, infraestrutura urbana, saneamento, perícia, gestão e empreendedorismo.', highlight: 'Formação para projetar e gerir obras em diálogo com o ambiente construído.' },
  'Engenharia de Alimentos': { description: 'Ciência e tecnologia para transformar matérias-primas em alimentos seguros e inovadores.', study: 'Química, microbiologia, processos, qualidade, embalagens, conservação e desenvolvimento de produtos.', work: 'Indústrias de alimentos, controle de qualidade, pesquisa, produção, consultoria e empreendedorismo.', highlight: 'Une engenharia, ciência dos alimentos e atenção à segurança alimentar.' },
  'Engenharia de Produção': { description: 'Projetos e processos para tornar organizações mais eficientes, sustentáveis e inovadoras.', study: 'Logística, qualidade, custos, operações, estatística, ergonomia, estratégia e inovação.', work: 'Indústria, serviços, consultoria, tecnologia, finanças, operações e gestão de projetos.', highlight: 'O foco é articular pessoas, tecnologia e processos para resolver problemas reais.' },
  'Engenharia Mecânica': { description: 'Máquinas, energia e processos industriais concebidos com base científica e criatividade.', study: 'Mecânica, materiais, termodinâmica, manufatura, automação, projeto e sistemas energéticos.', work: 'Indústria, automotivo, energia, manutenção, manufatura, pesquisa e desenvolvimento de produtos.', highlight: 'Formação ampla para atuar do projeto à produção e à inovação industrial.' },
  Farmácia: { description: 'Medicamentos, análises e cuidado em saúde ao longo de todo o seu ciclo de vida.', study: 'Fármacos, química, análises clínicas, tecnologia farmacêutica, cuidado farmacêutico e vigilância.', work: 'Farmácias, hospitais, laboratórios, indústria, pesquisa, vigilância sanitária e gestão.', highlight: 'Curso com laboratórios e práticas que aproximam ciência, tecnologia e atenção à saúde.' },
  Filosofia: { description: 'Investigação crítica das ideias, valores e fundamentos do conhecimento e da vida pública.', study: 'História da filosofia, ética, lógica, política, estética, epistemologia e pesquisa filosófica.', work: 'Ensino, pesquisa, editoração, políticas culturais, assessoria ética e produção de conteúdo.', highlight: 'Bacharelado e licenciatura formam pensamento rigoroso, argumentação e leitura crítica.' },
  Jornalismo: { description: 'Informação de interesse público, apuração responsável e narrativas para múltiplas plataformas.', study: 'Reportagem, ética, jornalismo de dados, audiovisual, fotojornalismo, edição e inovação.', work: 'Redações, assessoria, documentário, jornalismo de dados, comunicação pública e empreendedorismo.', highlight: 'A formação enfatiza verificação, diversidade de fontes e compromisso democrático.' },
  'Medicina Veterinária': { description: 'Saúde animal, saúde pública e produção responsável de alimentos de origem animal.', study: 'Clínica, cirurgia, prevenção, zoonoses, produção animal, alimentos, diagnóstico e bem-estar.', work: 'Clínicas, hospitais veterinários, agronegócio, vigilância, laboratórios, pesquisa e inspeção.', highlight: 'Atuação integrada entre animais, pessoas, ambiente e políticas de saúde.' },
  Odontologia: { description: 'Prevenção, diagnóstico e tratamento para promover saúde bucal ao longo da vida.', study: 'Anatomia, clínica, cirurgia, prótese, periodontia, odontopediatria, saúde coletiva e gestão.', work: 'Clínicas, hospitais, SUS, especialidades, pesquisa, ensino e gestão de serviços.', highlight: 'Prática clínica progressiva e atenção a diferentes necessidades de saúde da população.' },
  Pedagogia: { description: 'Educação, aprendizagem e gestão escolar para transformar experiências formativas.', study: 'Didática, políticas educacionais, infância, alfabetização, inclusão, currículo e gestão escolar.', work: 'Educação infantil, anos iniciais, gestão, coordenação, projetos sociais, pesquisa e formação.', highlight: 'Licenciatura que articula escola, território, diversidade e direito à educação.' },
  Psicologia: { description: 'Compreensão científica do comportamento, das relações e dos processos de subjetivação.', study: 'Desenvolvimento, clínica, psicologia social, pesquisa, avaliação, educação, trabalho e saúde.', work: 'Clínicas, escolas, organizações, hospitais, políticas públicas, pesquisa e assistência social.', highlight: 'Formação ética e plural, com estágios e práticas em diferentes contextos.' },
  'Relações Internacionais': { description: 'Política, economia e cooperação para compreender o mundo conectado e seus conflitos.', study: 'Política internacional, economia, direito, história, negociações, comércio e organizações globais.', work: 'Diplomacia, empresas, comércio exterior, ONGs, consultoria, pesquisa e organismos internacionais.', highlight: 'Formação interdisciplinar para interpretar desafios globais a partir do Brasil.' },
  'Serviço Social': { description: 'Direitos, políticas sociais e trabalho com comunidades para enfrentar desigualdades.', study: 'Política social, sociologia, economia, direitos humanos, ética, território e instrumentos de intervenção.', work: 'SUS, assistência social, educação, justiça, habitação, organizações sociais e pesquisa.', highlight: 'A profissão articula análise crítica, escuta qualificada e defesa de direitos.' },
  'Sistemas de Informação': { description: 'Tecnologia e gestão para criar sistemas que resolvem necessidades de organizações e pessoas.', study: 'Programação, bancos de dados, redes, engenharia de software, segurança, análise de processos e IA.', work: 'Desenvolvimento, produtos digitais, dados, infraestrutura, segurança, consultoria e inovação.', highlight: 'Integra computação e gestão, com projetos, laboratórios e conexão com a comunidade.' },
  Turismo: { description: 'Experiências, territórios e sustentabilidade para planejar viagens e destinos com responsabilidade.', study: 'Planejamento turístico, hospitalidade, patrimônio, economia, eventos, gestão e turismo de natureza.', work: 'Destinos, hotéis, agências, eventos, cultura, consultoria, setor público e empreendedorismo.', highlight: 'A formação dialoga com o território e com o potencial turístico regional.' },
  Zootecnia: { description: 'Ciência da produção animal com foco em bem-estar, eficiência e sustentabilidade.', study: 'Nutrição, genética, reprodução, manejo, pastagens, gestão, produtos de origem animal e ambiente.', work: 'Fazendas, cooperativas, agroindústria, consultoria, pesquisa, melhoramento e extensão rural.', highlight: 'O curso conecta ciência, produção responsável e desafios ambientais do campo.' },
};
const guideCourse = (name: string, city: string, area: string) => ({
  name, city, area,
  ...(detailedGuideCourses[name] ?? {
    description: `Formação em ${name} para compreender problemas contemporâneos e criar soluções na sua área.`,
    study: `Fundamentos, métodos e práticas profissionais de ${name}, com atividades teóricas e aplicadas.`,
    work: 'Setor público e privado, pesquisa, educação, inovação e projetos voltados à comunidade.',
    highlight: 'Consulte o Guia de Profissões para conhecer modalidades, unidades e características de cada oferta.',
  }),
});
const additionalCourses = [
  guideCourse('Administração Pública', 'Araraquara', 'Humanas'), guideCourse('Arquivologia', 'Marília', 'Humanas'), guideCourse('Arte-Teatro e Artes Cênicas', 'São Paulo', 'Artes'), guideCourse('Artes Visuais', 'Bauru · São Paulo', 'Artes'), guideCourse('Biblioteconomia', 'Marília', 'Humanas'), guideCourse('Ciências Biomédicas', 'Botucatu', 'Saúde'), guideCourse('Ciências Econômicas', 'Araraquara', 'Humanas'), guideCourse('Ciências Sociais', 'Araraquara · Marília', 'Humanas'), guideCourse('Comunicação: Rádio, TV e Internet', 'Bauru', 'Artes'), guideCourse('Ecologia', 'Rio Claro', 'Saúde'), guideCourse('Educação Física', 'Bauru · Presidente Prudente · Rio Claro', 'Saúde'), guideCourse('Enfermagem', 'Botucatu', 'Saúde'),
  guideCourse('Engenharia Aeronáutica', 'São João da Boa Vista', 'Exatas'), guideCourse('Engenharia Ambiental', 'Presidente Prudente · Rio Claro · São José dos Campos · Sorocaba', 'Exatas'), guideCourse('Engenharia Cartográfica e de Agrimensura', 'Presidente Prudente', 'Exatas'), guideCourse('Engenharia Civil', 'Bauru · Guaratinguetá · Ilha Solteira', 'Exatas'), guideCourse('Engenharia de Alimentos', 'São José do Rio Preto', 'Exatas'), guideCourse('Engenharia de Bioprocessos e Biotecnologia', 'Araraquara · Assis · Botucatu', 'Exatas'), guideCourse('Engenharia de Biossistemas', 'Tupã', 'Exatas'), guideCourse('Engenharia de Controle e Automação', 'Sorocaba', 'Exatas'), guideCourse('Engenharia de Energia', 'Rosana', 'Exatas'), guideCourse('Engenharia de Materiais', 'Guaratinguetá', 'Exatas'), guideCourse('Engenharia de Pesca', 'Registro', 'Exatas'), guideCourse('Engenharia de Produção', 'Bauru · Guaratinguetá · Itapeva', 'Exatas'), guideCourse('Engenharia Eletrônica e de Telecomunicações', 'São João da Boa Vista', 'Exatas'), guideCourse('Engenharia Elétrica', 'Bauru · Guaratinguetá · Ilha Solteira', 'Exatas'), guideCourse('Engenharia Florestal', 'Botucatu', 'Exatas'), guideCourse('Engenharia Industrial – Madeira', 'Itapeva', 'Exatas'), guideCourse('Engenharia Mecânica', 'Bauru · Guaratinguetá · Ilha Solteira', 'Exatas'), guideCourse('Engenharia Química', 'Araraquara', 'Exatas'),
  guideCourse('Estatística', 'Presidente Prudente', 'Exatas'), guideCourse('Farmácia', 'Araraquara', 'Saúde'), guideCourse('Filosofia', 'Marília', 'Humanas'), guideCourse('Física', 'Bauru · Guaratinguetá · Ilha Solteira · Presidente Prudente · Rio Claro · São José do Rio Preto', 'Exatas'), guideCourse('Física Médica', 'Botucatu', 'Saúde'), guideCourse('Fisioterapia', 'Marília · Presidente Prudente', 'Saúde'), guideCourse('Fonoaudiologia', 'Marília', 'Saúde'), guideCourse('Geografia', 'Ourinhos · Presidente Prudente · Rio Claro', 'Humanas'), guideCourse('Geologia', 'Rio Claro', 'Exatas'), guideCourse('História', 'Assis · Franca', 'Humanas'), guideCourse('Jornalismo', 'Bauru', 'Artes'), guideCourse('Letras', 'Araraquara · Assis · São José do Rio Preto', 'Humanas'), guideCourse('Letras – Tradução', 'São José do Rio Preto', 'Humanas'), guideCourse('Matemática', 'Bauru · Guaratinguetá · Ilha Solteira · Presidente Prudente · Rio Claro · São José do Rio Preto', 'Exatas'), guideCourse('Medicina Veterinária', 'Araçatuba · Botucatu · Jaboticabal', 'Saúde'), guideCourse('Meteorologia', 'Bauru', 'Exatas'), guideCourse('Nutrição', 'Botucatu', 'Saúde'), guideCourse('Odontologia', 'Araçatuba · Araraquara · São José dos Campos', 'Saúde'), guideCourse('Pedagogia', 'Araraquara · Bauru · Marília · Presidente Prudente · Rio Claro · São José do Rio Preto', 'Humanas'), guideCourse('Psicologia', 'Assis · Bauru', 'Saúde'), guideCourse('Química', 'Araraquara · Bauru · Presidente Prudente · São José do Rio Preto', 'Exatas'), guideCourse('Relações Internacionais', 'Franca · Marília', 'Humanas'), guideCourse('Relações Públicas', 'Bauru', 'Artes'), guideCourse('Serviço Social', 'Franca', 'Humanas'), guideCourse('Sistemas de Informação', 'Bauru', 'Tecnologia'), guideCourse('Terapia Ocupacional', 'Marília', 'Saúde'), guideCourse('Turismo', 'Rosana', 'Humanas'), guideCourse('Zootecnia', 'Botucatu · Dracena · Ilha Solteira · Jaboticabal', 'Saúde'),
];
const allCourses = [...courses, ...additionalCourses];
const areas = ['Todos', 'Tecnologia', 'Saúde', 'Humanas', 'Exatas', 'Artes'];

export default function Home() {
  const [query, setQuery] = useState('');
  const [area, setArea] = useState('Todos');
  const [selected, setSelected] = useState(() => allCourses.find((course) => course.name === 'Música')!);
  const results = useMemo(() => allCourses.filter((course) => {
    const matchesQuery = `${course.name} ${course.city} ${course.area}`.toLowerCase().includes(query.toLowerCase());
    return matchesQuery && (area === 'Todos' || course.area === area);
  }), [area, query]);

  return <main>
    <header className="topbar">
      <a className="brand" href="#inicio" aria-label="Vestibular Unesp 2027">UNESP <span>Vestibular 2027</span></a>
      <nav aria-label="Navegação principal"><a href="#cursos">Explorar cursos</a><a href="#detalhe">Ficha do curso</a></nav>
      <a className="button button-small" href={applicationUrl} target="_blank" rel="noreferrer">Inscreva-se</a>
    </header>
    <section id="inicio" className="hero">
      <p className="eyebrow">UNIVERSIDADE ESTADUAL PAULISTA</p><h1>Seu próximo lugar<br />é na UNESP.</h1>
      <p className="hero-copy">Escolha um curso, conheça a cidade e siga para a informação oficial. São 136 cursos de graduação em 24 cidades paulistas.</p>
      <div className="hero-actions"><a className="button" href="#cursos">Encontre seu curso <span>↓</span></a><a className="text-link" href={applicationUrl} target="_blank" rel="noreferrer">Ir para a inscrição na Vunesp <span>↗</span></a></div>
      <div className="hero-stat"><strong>5.850</strong><span>vagas para 2027</span></div>
    </section>
    <section id="datas" className="dates" aria-label="Datas principais"><div><span>Inscrições</span><strong>4 set. — 20 out.</strong></div><div><span>1ª fase</span><strong>22 nov. 2026</strong></div><div><span>2ª fase</span><strong>13 e 14 dez.</strong></div></section>
    <section id="cursos" className="course-section">
      <div className="section-head"><div><p className="eyebrow">CATÁLOGO COMPLETO DO GUIA</p><h2>Explore as 67 profissões<br />da UNESP.</h2></div><p>Busque, abra a ficha e siga para o Guia oficial ou para a inscrição. Uma ação por vez, sem se perder.</p></div>
      <label className="search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Busque por curso ou cidade" aria-label="Busque por curso ou cidade" /></label>
      <div className="filters" aria-label="Filtre por área">{areas.map((item) => <button key={item} className={area === item ? 'active' : ''} onClick={() => setArea(item)}>{item}</button>)}</div>
      <p className="result-count">{results.length} de {allCourses.length} profissões do Guia</p>
      <div className="course-grid">{results.map((course) => <article className="course-card" key={course.name}><p>{course.area}</p><h3>{course.name}</h3><span className="city">{course.city}</span><p className="description">{course.description}</p><button className="course-open" onClick={() => setSelected(course)}>Ver detalhes do curso <span>↓</span></button></article>)}</div>
      {results.length === 0 && <p className="empty">Não encontramos esse curso nesta seleção. Consulte o Guia de Profissões completo.</p>}
      <section id="detalhe" className="course-detail" aria-live="polite"><p className="eyebrow">CURSO EM DESTAQUE · {selected.area}</p><h3>{selected.name}</h3><p className="detail-city">{selected.city}</p><div><article><h4>O que você estuda</h4><p>{selected.study}</p></article><article><h4>Onde pode atuar</h4><p>{selected.work}</p></article><article><h4>Na UNESP</h4><p>{selected.highlight}</p></article></div>{selected.name === 'Música' && <section className="music-material"><p className="eyebrow">MATERIAL DA CAMPANHA</p><h4>Conheça Música na UNESP</h4><video controls poster="/musica-thumb.jpg"><source src="/musica-unesp.mp4" type="video/mp4" /></video></section>}<a className="button" href={guideUrl} target="_blank" rel="noreferrer">Conferir no Guia de Profissões <span>↗</span></a></section>
      <a className="guide-link" href={guideUrl} target="_blank" rel="noreferrer">Ver todos os cursos no Guia de Profissões <span>↗</span></a>
    </section>
    <section id="como-funciona" className="path"><p className="eyebrow">UMA JORNADA SEM DESVIO</p><h2>Da descoberta à inscrição<br />em três passos.</h2><ol><li><span>01</span><strong>Descubra</strong><p>Busque por área, curso ou cidade.</p></li><li><span>02</span><strong>Entenda</strong><p>Leia sobre a formação e os câmpus no Guia de Profissões.</p></li><li><span>03</span><strong>Inscreva-se</strong><p>Conclua a inscrição no ambiente oficial da Vunesp.</p></li></ol></section>
    <section className="callout"><p className="eyebrow">VESTIBULAR UNESP 2027</p><h2>O futuro começa com<br />uma escolha bem informada.</h2><a className="button button-light" href={applicationUrl} target="_blank" rel="noreferrer">Acessar inscrição oficial <span>↗</span></a></section>
    <footer>UNESP · Vestibular 2027 <span>Informações oficiais: Portal do Vestibular e Fundação Vunesp.</span></footer>
  </main>;
}
