'use client';

import { useMemo, useState } from 'react';

const applicationUrl = 'https://www.vunesp.com.br/VNSP2514';
const guideUrl = 'https://vestibular.unesp.br/Home/guiadeprofissoes51/guia-unesp-de-profissoes-2025-1.pdf';
const courses = [
  { name: 'Ciência da Computação', city: 'Bauru · Presidente Prudente · Rio Claro · São José do Rio Preto', area: 'Tecnologia', description: 'Algoritmos, programação e sistemas para resolver problemas complexos.', study: 'Lógica, matemática, algoritmos, programação, hardware e arquitetura de computadores.', work: 'Software, dados, inteligência artificial, segurança da informação, redes e computação em nuvem.', highlight: 'Há laboratórios, pesquisa e projetos práticos em todos os câmpus.' },
  { name: 'Direito', city: 'Franca', area: 'Humanas', description: 'Leitura crítica das normas e da vida social para promover justiça.', study: 'Constitucional, administrativo, penal, civil, trabalho, comercial e tributário, com base humanista.', work: 'Advocacia, concursos públicos, consultoria, assessoria legislativa, pesquisa e docência.', highlight: 'Prática jurídica, serviços à comunidade e acompanhamento de processos e audiências.' },
  { name: 'Engenharia Agronômica', city: 'Botucatu · Dracena · Ilha Solteira · Jaboticabal · Registro', area: 'Exatas', description: 'Ciência e tecnologia para a produção agrícola e animal sustentável.', study: 'Solo, plantas, produção, mecanização, economia rural, alimentos e gestão de projetos.', work: 'Agronegócio, cooperativas, agroindústrias, pesquisa, consultoria, mercado financeiro e propriedades rurais.', highlight: 'Fazendas experimentais, extensão e atuação conectada a territórios produtivos.' },
  { name: 'Medicina', city: 'Botucatu', area: 'Saúde', description: 'Formação científica e humanística para o cuidado integral em saúde.', study: 'Bases biológicas, fisiológicas e clínicas, integralidade do cuidado e habilidades médicas.', work: 'Atenção primária, urgência, hospitais, SUS, residência e diferentes especialidades.', highlight: 'Seis anos, com prática desde o início e internato de três anos.' },
  { name: 'Arquitetura e Urbanismo', city: 'Bauru · Presidente Prudente', area: 'Exatas', description: 'Projeto, cidade e território para tornar os lugares mais habitáveis.', study: 'Projeto, tecnologia, linguagem, práticas profissionais, urbanismo e patrimônio.', work: 'Construção, planejamento urbano e territorial, restauro, paisagismo e interiores.', highlight: 'Atividades de extensão tratam a cidade como laboratório de práticas aplicadas.' },
  { name: 'Ciências Biológicas', city: 'Assis · Bauru · Botucatu · Ilha Solteira · Jaboticabal · Rio Claro · São José do Rio Preto · São Vicente', area: 'Saúde', description: 'O estudo da vida, da biodiversidade e da relação humana com o ambiente.', study: 'Genética, biologia molecular, fauna, flora, ecologia, ambiente e educação.', work: 'Pesquisa, ensino, laboratórios, gestão ambiental, conservação, alimentos e vacinas.', highlight: 'Bacharelado e licenciatura; São Vicente oferece também ênfases em Biologia Marinha e Gerenciamento Costeiro.' },
  { name: 'Administração', city: 'Jaboticabal · Tupã', area: 'Humanas', description: 'Gestão estratégica de pessoas, recursos e organizações.', study: 'Finanças, produção, marketing, sistemas de informação, inovação e gestão ambiental.', work: 'Empresas, hospitais, escolas, organizações públicas, ONGs, marketing e novos negócios.', highlight: 'Intercâmbio, empresa júnior, pesquisa e projetos de extensão integram a formação.' },
  { name: 'Design', city: 'Bauru', area: 'Artes', description: 'Criatividade e tecnologia para melhorar produtos, sistemas e experiências.', study: 'Projetos visuais, produtos, interfaces, fotografia, ergonomia, fabricação digital e pesquisa.', work: 'Criação, direção de arte, conteúdo, curadoria, inovação, gestão e empreendedorismo.', highlight: 'Oficinas e laboratórios aproximam teoria, prática e experimentação.' },
];
const guideCourse = (name: string, city: string, area: string) => ({ name, city, area, description: `Conheça ${name}, seus câmpus e possibilidades de formação na UNESP.`, study: 'A ficha completa de formação, modalidades e unidades está no Guia de Profissões.', work: 'O Guia de Profissões apresenta campos de atuação e percursos de formação.', highlight: 'Selecione para ir ao Guia de Profissões oficial da UNESP.' });
const additionalCourses = [
  guideCourse('Administração Pública', 'Araraquara', 'Humanas'), guideCourse('Arquivologia', 'Marília', 'Humanas'), guideCourse('Arte-Teatro e Artes Cênicas', 'São Paulo', 'Artes'), guideCourse('Artes Visuais', 'Bauru · São Paulo', 'Artes'), guideCourse('Biblioteconomia', 'Marília', 'Humanas'), guideCourse('Ciências Biomédicas', 'Botucatu', 'Saúde'), guideCourse('Ciências Econômicas', 'Araraquara', 'Humanas'), guideCourse('Ciências Sociais', 'Araraquara · Marília', 'Humanas'), guideCourse('Comunicação: Rádio, TV e Internet', 'Bauru', 'Artes'), guideCourse('Ecologia', 'Rio Claro', 'Saúde'), guideCourse('Educação Física', 'Bauru · Presidente Prudente · Rio Claro', 'Saúde'), guideCourse('Enfermagem', 'Botucatu', 'Saúde'),
  guideCourse('Engenharia Aeronáutica', 'São João da Boa Vista', 'Exatas'), guideCourse('Engenharia Ambiental', 'Presidente Prudente · Rio Claro · São José dos Campos · Sorocaba', 'Exatas'), guideCourse('Engenharia Cartográfica e de Agrimensura', 'Presidente Prudente', 'Exatas'), guideCourse('Engenharia Civil', 'Bauru · Guaratinguetá · Ilha Solteira', 'Exatas'), guideCourse('Engenharia de Alimentos', 'São José do Rio Preto', 'Exatas'), guideCourse('Engenharia de Bioprocessos e Biotecnologia', 'Araraquara · Assis · Botucatu', 'Exatas'), guideCourse('Engenharia de Biossistemas', 'Tupã', 'Exatas'), guideCourse('Engenharia de Controle e Automação', 'Sorocaba', 'Exatas'), guideCourse('Engenharia de Energia', 'Rosana', 'Exatas'), guideCourse('Engenharia de Materiais', 'Guaratinguetá', 'Exatas'), guideCourse('Engenharia de Pesca', 'Registro', 'Exatas'), guideCourse('Engenharia de Produção', 'Bauru · Guaratinguetá · Itapeva', 'Exatas'), guideCourse('Engenharia Eletrônica e de Telecomunicações', 'São João da Boa Vista', 'Exatas'), guideCourse('Engenharia Elétrica', 'Bauru · Guaratinguetá · Ilha Solteira', 'Exatas'), guideCourse('Engenharia Florestal', 'Botucatu', 'Exatas'), guideCourse('Engenharia Industrial – Madeira', 'Itapeva', 'Exatas'), guideCourse('Engenharia Mecânica', 'Bauru · Guaratinguetá · Ilha Solteira', 'Exatas'), guideCourse('Engenharia Química', 'Araraquara', 'Exatas'),
  guideCourse('Estatística', 'Presidente Prudente', 'Exatas'), guideCourse('Farmácia', 'Araraquara', 'Saúde'), guideCourse('Filosofia', 'Marília', 'Humanas'), guideCourse('Física', 'Bauru · Guaratinguetá · Ilha Solteira · Presidente Prudente · Rio Claro · São José do Rio Preto', 'Exatas'), guideCourse('Física Médica', 'Botucatu', 'Saúde'), guideCourse('Fisioterapia', 'Marília · Presidente Prudente', 'Saúde'), guideCourse('Fonoaudiologia', 'Marília', 'Saúde'), guideCourse('Geografia', 'Ourinhos · Presidente Prudente · Rio Claro', 'Humanas'), guideCourse('Geologia', 'Rio Claro', 'Exatas'), guideCourse('História', 'Assis · Franca', 'Humanas'), guideCourse('Jornalismo', 'Bauru', 'Artes'), guideCourse('Letras', 'Araraquara · Assis · São José do Rio Preto', 'Humanas'), guideCourse('Letras – Tradução', 'São José do Rio Preto', 'Humanas'), guideCourse('Matemática', 'Bauru · Guaratinguetá · Ilha Solteira · Presidente Prudente · Rio Claro · São José do Rio Preto', 'Exatas'), guideCourse('Medicina Veterinária', 'Araçatuba · Botucatu · Jaboticabal', 'Saúde'), guideCourse('Meteorologia', 'Bauru', 'Exatas'), guideCourse('Música', 'São Paulo', 'Artes'), guideCourse('Nutrição', 'Botucatu', 'Saúde'), guideCourse('Odontologia', 'Araçatuba · Araraquara · São José dos Campos', 'Saúde'), guideCourse('Pedagogia', 'Araraquara · Bauru · Marília · Presidente Prudente · Rio Claro · São José do Rio Preto', 'Humanas'), guideCourse('Psicologia', 'Assis · Bauru', 'Saúde'), guideCourse('Química', 'Araraquara · Bauru · Presidente Prudente · São José do Rio Preto', 'Exatas'), guideCourse('Relações Internacionais', 'Franca · Marília', 'Humanas'), guideCourse('Relações Públicas', 'Bauru', 'Artes'), guideCourse('Serviço Social', 'Franca', 'Humanas'), guideCourse('Sistemas de Informação', 'Bauru', 'Tecnologia'), guideCourse('Terapia Ocupacional', 'Marília', 'Saúde'), guideCourse('Turismo', 'Rosana', 'Humanas'), guideCourse('Zootecnia', 'Botucatu · Dracena · Ilha Solteira · Jaboticabal', 'Saúde'),
];
const allCourses = [...courses, ...additionalCourses];
const areas = ['Todos', 'Tecnologia', 'Saúde', 'Humanas', 'Exatas', 'Artes'];

export default function Home() {
  const [query, setQuery] = useState('');
  const [area, setArea] = useState('Todos');
  const [selected, setSelected] = useState(courses[0]);
  const results = useMemo(() => allCourses.filter((course) => {
    const matchesQuery = `${course.name} ${course.city} ${course.area}`.toLowerCase().includes(query.toLowerCase());
    return matchesQuery && (area === 'Todos' || course.area === area);
  }), [area, query]);

  return <main>
    <header className="topbar">
      <a className="brand" href="#inicio" aria-label="Vestibular Unesp 2027">UNESP <span>Vestibular 2027</span></a>
      <nav aria-label="Navegação principal"><a href="#cursos">Explorar cursos</a><a href="#detalhe">Ficha do curso</a></nav>
      <a className="button button-small" href={applicationUrl} target="_blank" rel="noreferrer">Inscreva-se</a>
    </header>
    <section id="inicio" className="hero">
      <p className="eyebrow">UNIVERSIDADE ESTADUAL PAULISTA</p><h1>Seu próximo lugar<br />é na UNESP.</h1>
      <p className="hero-copy">Escolha um curso, conheça a cidade e siga para a informação oficial. São 136 cursos de graduação em 24 cidades paulistas.</p>
      <div className="hero-actions"><a className="button" href="#cursos">Encontre seu curso <span>↓</span></a><a className="text-link" href={applicationUrl} target="_blank" rel="noreferrer">Ir para a inscrição na Vunesp <span>↗</span></a></div>
      <div className="hero-stat"><strong>5.850</strong><span>vagas para 2027</span></div>
    </section>
    <section id="datas" className="dates" aria-label="Datas principais"><div><span>Inscrições</span><strong>4 set. — 20 out.</strong></div><div><span>1ª fase</span><strong>22 nov. 2026</strong></div><div><span>2ª fase</span><strong>13 e 14 dez.</strong></div></section>
    <section id="cursos" className="course-section">
      <div className="section-head"><div><p className="eyebrow">CATÁLOGO COMPLETO DO GUIA</p><h2>Explore as 67 profissões<br />da UNESP.</h2></div><p>Busque, abra a ficha e siga para o Guia oficial ou para a inscrição. Uma ação por vez, sem se perder.</p></div>
      <label className="search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Busque por curso ou cidade" aria-label="Busque por curso ou cidade" /></label>
      <div className="filters" aria-label="Filtre por área">{areas.map((item) => <button key={item} className={area === item ? 'active' : ''} onClick={() => setArea(item)}>{item}</button>)}</div>
      <p className="result-count">{results.length} de {allCourses.length} profissões do Guia</p>
      <div className="course-grid">{results.map((course) => <article className="course-card" key={course.name}><p>{course.area}</p><h3>{course.name}</h3><span className="city">{course.city}</span><p className="description">{course.description}</p><button className="course-open" onClick={() => setSelected(course)}>Ver detalhes do curso <span>↓</span></button></article>)}</div>
      {results.length === 0 && <p className="empty">Não encontramos esse curso nesta seleção. Consulte o Guia de Profissões completo.</p>}
      <section id="detalhe" className="course-detail" aria-live="polite"><p className="eyebrow">CURSO EM DESTAQUE · {selected.area}</p><h3>{selected.name}</h3><p className="detail-city">{selected.city}</p><div><article><h4>O que você estuda</h4><p>{selected.study}</p></article><article><h4>Onde pode atuar</h4><p>{selected.work}</p></article><article><h4>Na UNESP</h4><p>{selected.highlight}</p></article></div><a className="button" href={guideUrl} target="_blank" rel="noreferrer">Conferir no Guia de Profissões <span>↗</span></a></section>
      <a className="guide-link" href={guideUrl} target="_blank" rel="noreferrer">Ver todos os cursos no Guia de Profissões <span>↗</span></a>
    </section>
    <section id="como-funciona" className="path"><p className="eyebrow">UMA JORNADA SEM DESVIO</p><h2>Da descoberta à inscrição<br />em três passos.</h2><ol><li><span>01</span><strong>Descubra</strong><p>Busque por área, curso ou cidade.</p></li><li><span>02</span><strong>Entenda</strong><p>Leia sobre a formação e os câmpus no Guia de Profissões.</p></li><li><span>03</span><strong>Inscreva-se</strong><p>Conclua a inscrição no ambiente oficial da Vunesp.</p></li></ol></section>
    <section className="callout"><p className="eyebrow">VESTIBULAR UNESP 2027</p><h2>O futuro começa com<br />uma escolha bem informada.</h2><a className="button button-light" href={applicationUrl} target="_blank" rel="noreferrer">Acessar inscrição oficial <span>↗</span></a></section>
    <footer>UNESP · Vestibular 2027 <span>Informações oficiais: Portal do Vestibular e Fundação Vunesp.</span></footer>
  </main>;
}
